/**
 * Socket Authentication Middleware
 *
 * Authentication priority order:
 *   1. Better Auth session cookie from the WebSocket upgrade request headers.
 *      Socket.IO sends cookies automatically when `withCredentials: true` is set
 *      on the client and CORS is configured correctly on the server.
 *      On success: sets auth.playerId = user.id, auth.playerName = user.name.
 *   2. Existing guest ID (auth.playerId starting with "guest_") — for reconnection.
 *   3. No ID at all — gameManager will generate a new guest ID on connection.
 *
 * Known issue #1: If the Better Auth session cookie is present but invalid/expired,
 * the middleware silently falls through to guest mode. This is intentional — we
 * do not want a failed auth check to block the game connection. The user will
 * simply play as a guest and their stats won't be persisted.
 *
 * Why cookies work here:
 *   Better Auth sets an HttpOnly cookie (`better-auth.session_token`) that the
 *   browser attaches to every request to the server origin, including the Socket.IO
 *   WebSocket upgrade HTTP request. We forward these headers directly to
 *   auth.api.getSession() so Better Auth can validate the session normally.
 */

import type { Socket } from 'socket.io';
import jwt from 'jsonwebtoken';
import { auth } from '../../auth.js';
import { createLogger } from '../../utils/logger.js';
import { config } from '../../config/index.js';

const log = createLogger('socket-auth');

/** Regex for valid guest IDs as generated by gameManager (guest_ + nanoid(8)). */
const GUEST_ID_RE = /^guest_[a-zA-Z0-9_-]{8,}$/;

export async function socketAuthMiddleware(
    socket: Socket,
    next: (err?: Error) => void
): Promise<void> {
    const handshakeAuth = socket.handshake.auth as Record<string, unknown>;
    const token = handshakeAuth?.token as string | undefined;

    // Build a Headers object from the socket's HTTP upgrade request.
    // This includes the `cookie` header with `better-auth.session_token`.
    const requestHeaders = new Headers();
    const incomingHeaders = socket.handshake.headers;
    if (incomingHeaders.cookie) {
        requestHeaders.set('cookie', incomingHeaders.cookie as string);
    }

    const hasCookie = requestHeaders.has('cookie');
    log.debug({ socketId: socket.id, hasCookie, hasToken: !!token }, 'Socket auth check');

    // ── Step 1: Validate Better Auth session from upgrade request cookie ─────
    if (hasCookie) {
        try {
            const session = await auth.api.getSession({ headers: requestHeaders });

            if (session?.user) {
                log.info({ userId: session.user.id, name: session.user.name }, 'Socket authenticated via Better Auth cookie');
                // Override handshake auth so socketServer.ts picks up the real user ID.
                handshakeAuth.playerId    = session.user.id;
                handshakeAuth.playerName  = session.user.name;
                handshakeAuth.isAuthUser  = true;
                return next();
            }

            // Cookie present but session invalid/expired — DO NOT fall back to guest. Reject connection.
            log.warn({ socketId: socket.id }, 'Cookie present but no valid session — rejecting connection');
            return next(new Error('NOT_AUTHENTICATED'));
        } catch (err) {
            // Network/DB error checking session — reject connection to be safe.
            log.error(err, 'Error validating Better Auth cookie in socket middleware — rejecting connection');
            return next(new Error('NOT_AUTHENTICATED'));
        }
    }

    // ── Step 2: Validate existing guest token ────────────────────────────
    if (token) {
        try {
            // Use BETTER_AUTH_SECRET as the JWT secret
            const secret = config.BETTER_AUTH_SECRET;
            const decoded = jwt.verify(token, secret) as { playerId: string };
            
            if (decoded.playerId && GUEST_ID_RE.test(decoded.playerId)) {
                log.info({ socketId: socket.id, playerId: decoded.playerId }, 'Socket authenticated via Guest JWT');
                handshakeAuth.playerId = decoded.playerId;
                handshakeAuth.isAuthUser = false;
                return next();
            }
        } catch (err) {
            log.warn({ socketId: socket.id }, 'Invalid/Expired Guest JWT — stripping so a new one is assigned');
            delete handshakeAuth.playerId;
            delete handshakeAuth.token;
        }
    } else {
        // Strip any unverified playerId sent from client just in case
        delete handshakeAuth.playerId;
    }

    // ── Step 3: Allow connection (new guest mode) ────────────────────────────────
    handshakeAuth.isAuthUser = false;
    next();
}

export default socketAuthMiddleware;
